[manager]

keymap = [
	# Cancel
	{ on = [ "<Esc>" ], exec = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "q" ], exec = "close",              desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "Q" ],     exec = "quit",               desc = "Exit the process" },
	{ on = [ "<C-q>" ],     exec = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },

	# Navigation
	{ on = [ "j" ], exec = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "k" ], exec = "arrow -1", desc = "Move cursor up" },
	{ on = [ "J" ], exec = "arrow 5",  desc = "Move cursor down 5 lines" },
	{ on = [ "K" ], exec = "arrow -5", desc = "Move cursor up 5 lines" },
	{ on = [ "<C-j>" ], exec = "arrow 50%",   desc = "Move cursor down half page" },
	{ on = [ "<C-k>" ], exec = "arrow -50%",  desc = "Move cursor up half page" },
	{ on = [ "h" ], exec = [ "leave", "escape --visual --select" ], desc = "Go back to the parent directory" },
	{ on = [ "l" ], exec = [ "enter", "escape --visual --select" ], desc = "Enter the child directory" },
	{ on = [ "H" ], exec = "back",    desc = "Go back to the previous directory" },
	{ on = [ "L" ], exec = "forward", desc = "Go forward to the next directory" },
	{ on = [ "<Down>" ],  exec = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "<Up>" ],    exec = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Left>" ],  exec = "leave",    desc = "Go back to the parent directory" },
	{ on = [ "<Right>" ], exec = "enter",    desc = "Enter the child directory" },
	{ on = [ "g", "g" ], exec = "arrow -99999999", desc = "Move cursor to the top" },
	{ on = [ "G" ],      exec = "arrow 99999999",  desc = "Move cursor to the bottom" },

	# Tabs
	{ on = [ "t", "t" ], exec = "tab_create --current", desc = "Create a new tab using the current path" },
	{ on = [ "t", "1" ], exec = "tab_switch 0", desc = "Switch to the first tab" },
	{ on = [ "t", "2" ], exec = "tab_switch 1", desc = "Switch to the second tab" },
	{ on = [ "t", "3" ], exec = "tab_switch 2", desc = "Switch to the third tab" },
	{ on = [ "t", "4" ], exec = "tab_switch 3", desc = "Switch to the fourth tab" },
	{ on = [ "t", "5" ], exec = "tab_switch 4", desc = "Switch to the fifth tab" },
	{ on = [ "t", "6" ], exec = "tab_switch 5", desc = "Switch to the sixth tab" },
	{ on = [ "t", "7" ], exec = "tab_switch 6", desc = "Switch to the seventh tab" },
	{ on = [ "t", "8" ], exec = "tab_switch 7", desc = "Switch to the eighth tab" },
	{ on = [ "t", "9" ], exec = "tab_switch 8", desc = "Switch to the ninth tab" },
	{ on = [ "<C-h>" ], exec = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
	{ on = [ "<C-l>" ], exec = "tab_switch 1 --relative",  desc = "Switch to the next tab" },
	{ on = [ "t", "h" ], exec = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
	{ on = [ "t", "l" ], exec = "tab_switch 1 --relative",  desc = "Switch to the next tab" },
	{ on = [ "t", "H" ], exec = "tab_swap -1", desc = "Swap the current tab with the previous tab" },
	{ on = [ "t", "L" ], exec = "tab_swap 1",  desc = "Swap the current tab with the next tab" },

	# Operation
	{ on = [ "<Enter>" ],   exec = "open",                                                 desc = "Open the selected files" },
	{ on = [ "r" ], exec = "open --interactive",                                   desc = "Open the selected files interactively" },
	{ on = [ "z", "h" ],         exec = "hidden toggle",                                        desc = "Toggle the visibility of hidden files" },
	{ on = [ ";" ],         exec = "shell",                                                desc = "Run a shell command" },
	{ on = [ ":" ],         exec = "shell --block",                                        desc = "Run a shell command (block the UI until the command finishes)" },
	{ on = [ "S" ],         exec = "shell zsh --block --confirm",                                                desc = "Run a shell command" },

	# Selection
	{ on = [ "<Space>" ], exec = [ "select --state=none", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = [ "v", "s" ],       exec = "select_all --state=true",           desc = "Select of all files" },
	{ on = [ "v", "x" ],       exec = "select_all --state=false",           desc = "Unselect of all files" },
	{ on = [ "v", "<Space>" ],   exec = "select_all --state=none",            desc = "Toggle selection of all files" },
	{ on = [ "v", "v" ],       exec = "visual_mode",                        desc = "Enter visual mode (selection mode)" },
	{ on = [ "v", "V" ],       exec = "visual_mode --unset",                desc = "Enter visual mode (unset mode)" },

	# Copy, Paste, Delete, Create, Link
	{ on = [ "y", "y" ],         exec = [ "yank", "escape --visual --select" ],                 desc = "Copy the selected files" },
	{ on = [ "y", "Y" ],         exec = [ "unyank", "escape --visual --select" ],               desc = "Cancel the yank status of files" },
	{ on = [ "p", "p" ],         exec = "paste",                                                desc = "Paste the files" },
	{ on = [ "p", "P" ],         exec = "paste --force",                                        desc = "Paste the files (overwrite if the destination exists)" },
	{ on = [ "d", "d" ],         exec = [ "yank --cut", "escape --visual --select" ],           desc = "Cut the selected files" },
	{ on = [ "d", "D" ],         exec = [ "remove", "escape --visual --select" ],               desc = "Move the files to the trash" },
	{ on = [ "D", "D" ],         exec = [ "remove --permanently", "escape --visual --select" ], desc = "Permanently delete the files" },
	{ on = [ "T" ],         exec = "create",                                               desc = "Create a file or directory (ends with / for directories)" },
	{ on = [ "-" ],         exec = "link",                                                 desc = "Symlink the absolute path of files" },
	{ on = [ "_" ],         exec = "link --relative",                                      desc = "Symlink the relative path of files" },

	# Path, Filename
	{ on = [ "y", "p" ], exec = "copy path",             desc = "Copy the absolute path" },
	{ on = [ "y", "d" ], exec = "copy dirname",          desc = "Copy the path of the parent directory" },
	{ on = [ "y", "n" ], exec = "copy filename",         desc = "Copy the name of the file" },
	{ on = [ "y", "N" ], exec = "copy name_without_ext", desc = "Copy the name of the file without the extension" },
	{ on = [ "c", "w" ],         exec = "rename --empty=all",                           desc = "Rename all" },
	{ on = [ "c", "n" ],         exec = "rename --empty=stem --cursor=start",                           desc = "Rename base" },
	{ on = [ "c", "N" ],         exec = "rename --empty=all",                           desc = "Rename all" },
	{ on = [ "c", "a" ],         exec = "rename --cursor=before_ext",                           desc = "Rename append base" },
	{ on = [ "c", "A" ],         exec = "rename --cursor=end",                           desc = "Rename append" },
	{ on = [ "c", "p" ],         exec = "rename --cursor=start",                           desc = "Rename prepend" },
	{ on = [ "c", "e" ],         exec = "rename --empty=ext --cursor=end",                           desc = "Rename extension" },

	# Find and Filter
	{ on = [ "f", "f" ], exec = "filter --smart", desc = "Filter the files" },
	{ on = [ "/" ], exec = "find --smart",            desc = "Find next file" },
	{ on = [ "?" ], exec = "find --previous --smart", desc = "Find previous file" },
	{ on = [ "n" ], exec = "find_arrow",              desc = "Go to next found file" },
	{ on = [ "N" ], exec = "find_arrow --previous",   desc = "Go to previous found file" },
	{ on = [ "f", "d" ],         exec = "search fd",                                            desc = "Search files by name using fd" },
	{ on = [ "f", "z" ],         exec = "jump fzf",                                             desc = "Jump to a directory, or reveal a file using fzf" },
	{ on = [ "<C-f>" ],         exec = "jump fzf",                                             desc = "Jump to a directory, or reveal a file using fzf" },

	# Linemode
	{ on = [ "i", "s" ], exec = "linemode size",        desc = "Set linemode to size" },
	{ on = [ "i", "m" ], exec = "linemode permissions", desc = "Set linemode to permissions" },
	{ on = [ "i", "t" ], exec = "linemode mtime",       desc = "Set linemode to mtime" },
	{ on = [ "i", "i" ], exec = "linemode none",        desc = "Set linemode to none" },

	# Sorting
	{ on = [ "s", "m" ], exec = "sort modified --dir-first",               desc = "Sort by modified time" },
	{ on = [ "s", "M" ], exec = "sort modified --reverse --dir-first",     desc = "Sort by modified time (reverse)" },
	{ on = [ "s", "c" ], exec = "sort created --dir-first",                desc = "Sort by created time" },
	{ on = [ "s", "C" ], exec = "sort created --reverse --dir-first",      desc = "Sort by created time (reverse)" },
	{ on = [ "s", "e" ], exec = "sort extension --dir-first",         	   desc = "Sort by extension" },
	{ on = [ "s", "E" ], exec = "sort extension --reverse --dir-first",    desc = "Sort by extension (reverse)" },
	{ on = [ "s", "a" ], exec = "sort alphabetical --dir-first",           desc = "Sort alphabetically" },
	{ on = [ "s", "A" ], exec = "sort alphabetical --reverse --dir-first", desc = "Sort alphabetically (reverse)" },
	{ on = [ "s", "n" ], exec = "sort natural --dir-first",                desc = "Sort naturally" },
	{ on = [ "s", "N" ], exec = "sort natural --reverse --dir-first",      desc = "Sort naturally (reverse)" },
	{ on = [ "s", "s" ], exec = "sort size --dir-first",                   desc = "Sort by size" },
	{ on = [ "s", "S" ], exec = "sort size --reverse --dir-first",         desc = "Sort by size (reverse)" },

	# Goto
	{ on = [ "g", "h" ],       exec = "cd ~",             desc = "Go to the home directory" },
	{ on = [ "g", "D" ],       exec = "cd ~/Desktop",             desc = "Go to the desktop directory" },
	{ on = [ "g", "c" ],       exec = "cd ~/.config",     desc = "Go to the config directory" },
	{ on = [ "g", "d" ],       exec = "cd ~/Downloads",   desc = "Go to the downloads directory" },
	{ on = [ "g", "t" ],       exec = "cd /tmp",          desc = "Go to the temporary directory" },
	{ on = [ "g", "p" ],       exec = "cd -",          desc = "Go to the previous directory" },
	{ on = [ "g", "<Space>" ], exec = "cd --interactive", desc = "Go to a directory interactively" },
	{ on = [ "c", "d" ], exec = "cd --interactive", desc = "Go to a directory interactively" },

	# Tasks
	{ on = [ "w" ], exec = "tasks_show", desc = "Show the tasks manager" },

	# Helo
	{ on = [ "~" ], exec = "help", desc = "Open help" }
]

[tasks]

keymap = [
	{ on = [ "<Esc>" ], exec = "close", desc = "Hide the task manager" },
	{ on = [ "w" ],     exec = "close", desc = "Hide the task manager" },

	{ on = [ "j" ], exec = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "k" ], exec = "arrow -1", desc = "Move cursor up" },
	{ on = [ "J" ], exec = "arrow 1",  desc = "Move cursor down 5 lines" },
	{ on = [ "K" ], exec = "arrow -1", desc = "Move cursor up 5 lines" },

	{ on = [ "<Enter>" ], exec = "inspect", desc = "Inspect the task" },
	{ on = [ "d", "d" ],       exec = "cancel",  desc = "Cancel the task" },

	{ on = [ "~" ], exec = "help", desc = "Open help" }
]

[select]

keymap = [
	{ on = [ "<Esc>" ],   exec = "close",          desc = "Cancel selection" },
	{ on = [ "<Enter>" ], exec = "close --submit", desc = "Submit the selection" },

	{ on = [ "j" ], exec = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "k" ], exec = "arrow -1", desc = "Move cursor up" },
	{ on = [ "J" ], exec = "arrow 5",  desc = "Move cursor down 5 lines" },
	{ on = [ "K" ], exec = "arrow -5", desc = "Move cursor up 5 lines" },

	{ on = [ "~" ], exec = "help", desc = "Open help" }
]

[input]

keymap = [
	{ on = [ "<Esc>" ],   exec = "escape",         desc = "Go back the normal mode, or cancel input" },
	{ on = [ "<Enter>" ], exec = "close --submit", desc = "Submit the input" },

	# Mode
	{ on = [ "i" ], exec = "insert",                              desc = "Enter insert mode" },
	{ on = [ "a" ], exec = "insert --append",                     desc = "Enter append mode" },
	{ on = [ "I" ], exec = [ "move -999", "insert" ],             desc = "Move to the BOL, and enter insert mode" },
	{ on = [ "A" ], exec = [ "move 999", "insert --append" ],     desc = "Move to the EOL, and enter append mode" },
	{ on = [ "v" ], exec = "visual",                              desc = "Enter visual mode" },
	{ on = [ "V" ], exec = [ "move -999", "visual", "move 999" ], desc = "Enter visual mode and select all" },

	# Character-wise movement
	{ on = [ "h" ],       exec = "move -1", desc = "Move back a character" },
	{ on = [ "l" ],       exec = "move 1",  desc = "Move forward a character" },
	{ on = [ "H" ],       exec = "move -3", desc = "Move back 3 character" },
	{ on = [ "L" ],       exec = "move 3",  desc = "Move forward 3 character" },

	# Word-wise movement
	{ on = [ "b" ],     exec = "backward",              desc = "Move back to the start of the current or previous word" },
	{ on = [ "w" ],     exec = "forward",               desc = "Move forward to the start of the next word" },
	{ on = [ "e" ],     exec = "forward --end-of-word", desc = "Move forward to the end of the current or next word" },
	{ on = [ "B" ],     exec = [ "backward", "backward", "backward" ],              desc = "Move 3 back to the start of the current or previous word" },
	{ on = [ "W" ],     exec = [ "forward", "forward", "forward" ],               desc = "Move 3 forward to the start of the next word" },
	{ on = [ "E" ],     exec = [ "forward --end-of-word", "forward --end-of-word", "forward --end-of-word" ], desc = "Move 3 forward to the end of the current or next word" },

	# Line-wise movement
	{ on = [ "0" ],     exec = "move -999", desc = "Move to the BOL" },
	{ on = [ "$" ],     exec = "move 999",  desc = "Move to the EOL" },
	{ on = [ "," ],     exec = "move -999", desc = "Move to the BOL" },
	{ on = [ "." ],     exec = "move 999",  desc = "Move to the EOL" },

	# Delete
	{ on = [ "<Backspace>" ], exec = "backspace",			desc = "Delete the character before the cursor" },

	# Cut/Yank/Paste
	{ on = [ "d" ], exec = "delete --cut",                              desc = "Cut the selected characters" },
	{ on = [ "D" ], exec = [ "delete --cut", "move 999" ],              desc = "Cut until the EOL" },
	{ on = [ "c" ], exec = "delete --cut --insert",                     desc = "Cut the selected characters, and enter insert mode" },
	{ on = [ "C" ], exec = [ "delete --cut --insert", "move 999" ],     desc = "Cut until the EOL, and enter insert mode" },
	{ on = [ "y" ], exec = "yank",           desc = "Copy the selected characters" },
	{ on = [ "p" ], exec = "paste",          desc = "Paste the copied characters after the cursor" },
	{ on = [ "P" ], exec = "paste --before", desc = "Paste the copied characters before the cursor" },

	# Undo/Redo
	{ on = [ "u" ], exec = "undo", desc = "Undo the last operation" },
	{ on = [ "U" ],	exec = "redo", desc = "Redo the last operation" },

	# Help
	{ on = [ "~" ], exec = "help", desc = "Open help" }
]

[completion]

keymap = [
	{ on = [ "<Esc>" ],   exec = "close",                                      desc = "Cancel completion" },
	{ on = [ "<Enter>" ],   exec = "close --submit",                             desc = "Submit the completion" },

	{ on = [ "<Tab>" ], exec = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "<BackTab>" ], exec = "arrow -1", desc = "Move cursor up" },

	{ on = [ "<C-j>" ], exec = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "<C-k>" ], exec = "arrow -1", desc = "Move cursor up" },

	{ on = [ "~" ], exec = "help", desc = "Open help" }
]

[help]

keymap = [
	{ on = [ "<Esc>" ], exec = "escape", desc = "Clear the filter, or hide the help" },
	{ on = [ "q" ],     exec = "close",  desc = "Exit the process" },

	# Navigation
	{ on = [ "k" ], exec = "arrow -1", desc = "Move cursor up" },
	{ on = [ "j" ], exec = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "K" ], exec = "arrow -5", desc = "Move cursor up 5 lines" },
	{ on = [ "J" ], exec = "arrow 5",  desc = "Move cursor down 5 lines" },

	# Filtering
	{ on = [ "f", "f" ], exec = "filter", desc = "Apply a filter for the help items" },
	{ on = [ "/" ], exec = "filter", desc = "Apply a filter for the help items" },
]
